name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-20.04,
          # macos-10.15,
          windows-2022
        ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.0'
          java-version: '17'
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Execute dist build
        run: ./gradle/gradlew --info clean createDist
      - name: Upload mac dist as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdx_unlimiter-mac
          path: build/pdx_unlimiter-mac.zip
          if-no-files-found: ignore
      - name: Upload Windows dist as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdx_unlimiter-windows
          path: build/pdx_unlimiter-windows.zip
          if-no-files-found: ignore
      - name: Upload Linux dist as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdx_unlimiter-linux
          path: build/pdx_unlimiter-linux.zip
          if-no-files-found: ignore
